before_script:
    - >
      apt-get update -qq && apt-get install -y -qq iptables-dev libevent-dev
      libnfnetlink-dev uuid-dev make gcc gcc-mingw-w64-i686 mingw-w64-tools
      libnftnl-dev libmnl-dev libssl-dev net-tools doxygen graphviz

stages:
    - build

job_miniupnpd:
    stage: build
    script:
        - "cd miniupnpd"
        - "./configure"
        - "make -j3 && make check"
        - "make dox"
        - "make clean"
        - "./configure --firewall=nftables"
        - "make -j3"

# i686-w64-mingw32-gcc
job_miniupnpc:
    stage: build
    script:
        - "cd miniupnpc && make -j3 && make check"
        - "make clean"
        - "make -f Makefile.mingw DLLWRAP=i686-w64-mingw32-dllwrap WINDRES=i686-w64-mingw32-windres CC=i686-w64-mingw32-gcc AR=i686-w64-mingw32-ar"
